package processing.mode.lua;

import processing.app.Sketch;
import processing.app.SketchCode;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;

/**
 * Exports a sketch for Roblox or LOVE2D.
 *
 * <p><b>Roblox:</b> Produces a single {@code .lua} file to drop into a
 * LocalScript in Roblox Studio, with the backend require boilerplate prepended.
 * The file is self-contained; the developer only needs two ModuleScripts in
 * ReplicatedStorage ({@code Processing} and {@code ProcessingBackendRoblox}).</p>
 *
 * <p><b>LOVE2D:</b> Produces a self-contained LOVE2D game folder:
 * <pre>
 *   &lt;SketchName&gt;/
 *     main.lua          ← wires up processing.lua + love2d backend, loads sketch
 *     &lt;SketchName&gt;.lua  ← the sketch source (all tabs concatenated)
 *     processing/       ← copy of mode/lua/ (processing.lua + backends/)
 * </pre>
 * Run it with {@code love &lt;SketchName&gt;/}.</p>
 *
 * <p>This class has no dependency on libprocessing, LuaJIT, or the Processing
 * IDE runtime — it is pure source-text assembly and file I/O.</p>
 */
public final class LuaExporter {

    // ── Roblox ────────────────────────────────────────────────────────────────

    private static final String ROBLOX_HEADER =
        "--[[\n" +
        "  Generated by Processing Lua Mode\n" +
        "  Drop this file into a LocalScript in Roblox Studio.\n" +
        "\n" +
        "  Required in ReplicatedStorage:\n" +
        "    Processing               → processing.lua\n" +
        "    ProcessingBackendRoblox  → backends/roblox.lua\n" +
        "]]\n" +
        "\n" +
        "local P       = require(game.ReplicatedStorage.Processing)\n" +
        "local Backend = require(game.ReplicatedStorage.ProcessingBackendRoblox)\n" +
        "P.setBackend(Backend)\n" +
        "P.inject(_ENV)\n" +
        "\n";

    private LuaExporter() {}

    /**
     * Assemble all sketch tabs and write a Roblox LocalScript to {@code dest}.
     *
     * @param sketch the current sketch
     * @param dest   target .lua file (created or overwritten)
     */
    public static void exportRoblox(Sketch sketch, File dest) throws IOException {
        StringBuilder sb = new StringBuilder();
        sb.append(ROBLOX_HEADER);
        appendTabs(sketch, sb);
        sb.append("\nP.run()\n");
        Files.writeString(dest.toPath(), sb.toString(), StandardCharsets.UTF_8);
    }

    // ── LOVE2D ────────────────────────────────────────────────────────────────

    /**
     * Export a self-contained LOVE2D game folder to {@code destDir}.
     *
     * <p>The folder is created if it does not exist; existing files are
     * overwritten.  The caller is responsible for ensuring {@code modeFolder}
     * points to the installed mode folder so we can copy {@code mode/lua/}.</p>
     *
     * @param sketch     the current sketch
     * @param destDir    target directory (will be created if absent)
     * @param modeFolder the mode's installed folder (parent of {@code mode/lua/})
     */
    public static void exportLove2d(Sketch sketch, File destDir, File modeFolder)
            throws IOException {
        destDir.mkdirs();

        String sketchName = sketch.getName();

        // 1. Write concatenated sketch source
        StringBuilder sketchSrc = new StringBuilder();
        appendTabs(sketch, sketchSrc);
        File sketchFile = new File(destDir, sketchName + ".lua");
        Files.writeString(sketchFile.toPath(), sketchSrc.toString(), StandardCharsets.UTF_8);

        // 2. Copy processing.lua + backends/ into destDir/processing/
        // In the installed mode layout: modeFolder/mode/lua/
        // In the development layout: modeFolder/../mode/lua/ (where modeFolder is the mode/ subdir)
        File luaSrc = new File(modeFolder, "mode/lua");
        if (!luaSrc.exists()) {
            // Dev fallback: modeFolder *is* the mode/ directory
            luaSrc = new File(modeFolder, "lua");
        }
        File luaDest = new File(destDir, "processing");
        copyDirectory(luaSrc, luaDest);

        // 3. Write a self-contained main.lua that wires everything up
        String mainLua =
            "--[[\n" +
            "  Generated by Processing Lua Mode\n" +
            "  Run with:  love " + destDir.getName() + "/\n" +
            "]]\n" +
            "\n" +
            "-- Add the bundled processing library to the search path\n" +
            "package.path = love.filesystem.getSource() .. \"/processing/?.lua;\"\n" +
            "            .. love.filesystem.getSource() .. \"/processing/?/init.lua;\"\n" +
            "            .. package.path\n" +
            "\n" +
            "local Processing = require(\"processing\")\n" +
            "local Love2DBack = require(\"backends.love2d\")\n" +
            "Processing.setBackend(Love2DBack)\n" +
            "\n" +
            "-- Load the sketch\n" +
            "local chunk, err = loadfile(love.filesystem.getSource() .. \"/" + sketchName + ".lua\")\n" +
            "if not chunk then\n" +
            "    io.stderr:write(\"lua: \" .. tostring(err) .. \"\\n\")\n" +
            "    love.event.quit(1)\n" +
            "    return\n" +
            "end\n" +
            "\n" +
            "local sketchEnv = setmetatable({}, { __index = _G })\n" +
            "setfenv(chunk, sketchEnv)\n" +
            "local ok, runErr = pcall(chunk)\n" +
            "if not ok then\n" +
            "    io.stderr:write(\"lua: \" .. tostring(runErr) .. \"\\n\")\n" +
            "    love.event.quit(1)\n" +
            "    return\n" +
            "end\n" +
            "\n" +
            "Processing.run(sketchEnv)\n";

        Files.writeString(new File(destDir, "main.lua").toPath(),
                          mainLua, StandardCharsets.UTF_8);

        // 4. Write a minimal conf.lua so LOVE2D starts with a hidden window
        //    (the sketch's size() call reveals it)
        String confLua =
            "function love.conf(t)\n" +
            "    t.window.title   = \"" + sketchName + "\"\n" +
            "    t.window.width   = 640\n" +
            "    t.window.height  = 480\n" +
            "    t.window.visible = false\n" +
            "end\n";

        Files.writeString(new File(destDir, "conf.lua").toPath(),
                          confLua, StandardCharsets.UTF_8);
    }

    // ── Shared helpers ────────────────────────────────────────────────────────

    /** Append all non-blank sketch tabs to {@code sb} with separator comments. */
    private static void appendTabs(Sketch sketch, StringBuilder sb) {
        for (SketchCode code : sketch.getCode()) {
            String prog = code.getProgram();
            if (prog == null || prog.isBlank()) continue;
            sb.append("\n-- === ").append(code.getPrettyName()).append(" ===\n\n");
            sb.append(prog);
            if (!prog.endsWith("\n")) sb.append('\n');
        }
    }

    /** Package-private hook for tests — delegates to {@link #copyDirectory}. */
    static void testCopyDirectory(File src, File dest) throws IOException {
        copyDirectory(src, dest);
    }

    /**
     * Package-private hook for tests — exercises the tab concatenation logic
     * of {@link #appendTabs} without needing a real {@code Sketch}.
     *
     * @param prettyNames tab display names (parallel to {@code programs})
     * @param programs    tab source text; {@code null} entries are treated as blank
     */
    static String testBuildTabSource(String[] prettyNames, String[] programs) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < prettyNames.length; i++) {
            String prog = programs[i];
            if (prog == null || prog.isBlank()) continue;
            sb.append("\n-- === ").append(prettyNames[i]).append(" ===\n\n");
            sb.append(prog);
            if (!prog.endsWith("\n")) sb.append('\n');
        }
        return sb.toString();
    }

    /** Recursively copy {@code src} directory to {@code dest}. */
    private static void copyDirectory(File src, File dest) throws IOException {
        if (!src.exists()) return;
        dest.mkdirs();
        File[] children = src.listFiles();
        if (children == null) return;
        for (File child : children) {
            File target = new File(dest, child.getName());
            if (child.isDirectory()) {
                copyDirectory(child, target);
            } else {
                Files.copy(child.toPath(), target.toPath(),
                           java.nio.file.StandardCopyOption.REPLACE_EXISTING);
            }
        }
    }
}
