--[[
  Processing for Lua — LOVE2D Backend
  For desktop testing outside the Processing IDE.

  The Processing IDE uses luamode-runner (a native Rust binary) which pre-registers
  all Processing globals directly via mlua and drives the event loop through the
  same App builder that libprocessing uses internally.  This backend is for
  standalone LOVE2D usage only.

  Usage (standalone with LOVE2D):
    Install LOVE2D, then:
      love . --sketch examples/bouncing_balls.lua

    Inside main.lua (generated by the launcher):
      local P = require("processing")
      P.setBackend(require("backends.love2d"))
      P.inject(_ENV)
      -- sketch functions defined here or loaded from --sketch arg
      P.run()
]]

local Backend = {}

local _startTime = 0
local _pState    = nil
local _P         = nil
local _env       = nil

-- ============================================================
-- Color conversion
-- ============================================================

-- Safely call love.graphics.setColor even if called outside draw
local function setFill(c)
  love.graphics.setColor(c.r, c.g, c.b, c.a)
end

local function setStroke(ds)
  love.graphics.setColor(
    ds.strokeColor.r,
    ds.strokeColor.g,
    ds.strokeColor.b,
    ds.strokeColor.a
  )
  love.graphics.setLineWidth(ds.strokeWeight)
end

-- ============================================================
-- Canvas
-- ============================================================

function Backend.init(pState)
  _pState    = pState
  _startTime = love.timer.getTime()
end

function Backend.createCanvas(w, h)
  love.window.setMode(w, h, {
    resizable = false,
    vsync     = 1,
    msaa      = 4,
  })
  love.window.setTitle("Processing for Lua")
  love.window.setVisible(true)    -- reveal the window now that size() has run
end

-- ============================================================
-- Drawing
-- ============================================================

function Backend.background(c)
  love.graphics.clear(c.r, c.g, c.b, c.a)
end

function Backend.point(x, y, ds)
  if not ds.hasStroke then return end
  setStroke(ds)
  local w = ds.strokeWeight
  love.graphics.rectangle("fill", x - w*0.5, y - w*0.5, w, w)
end

function Backend.line(x1, y1, x2, y2, ds)
  if not ds.hasStroke then return end
  setStroke(ds)
  love.graphics.line(x1, y1, x2, y2)
end

function Backend.rect(x1, y1, x2, y2, x3, y3, x4, y4, w, h, cornerR, ds)
  -- For axis-aligned (no rotation) use LOVE's native rectangle
  local isAA = math.abs(y2 - y1) < 0.5 and math.abs(x4 - x1) < 0.5
  if isAA then
    local lx = math.min(x1, x2, x3, x4)
    local ty = math.min(y1, y2, y3, y4)
    local rw = math.abs(w)
    local rh = math.abs(h)
    if ds.hasFill then
      setFill(ds.fillColor)
      if cornerR > 0 then
        love.graphics.rectangle("fill", lx, ty, rw, rh, cornerR, cornerR, 12)
      else
        love.graphics.rectangle("fill", lx, ty, rw, rh)
      end
    end
    if ds.hasStroke then
      setStroke(ds)
      if cornerR > 0 then
        love.graphics.rectangle("line", lx, ty, rw, rh, cornerR, cornerR, 12)
      else
        love.graphics.rectangle("line", lx, ty, rw, rh)
      end
    end
  else
    -- Rotated rect: draw as polygon
    local pts = { x1, y1, x2, y2, x3, y3, x4, y4 }
    if ds.hasFill then
      setFill(ds.fillColor)
      love.graphics.polygon("fill", pts)
    end
    if ds.hasStroke then
      setStroke(ds)
      love.graphics.polygon("line", pts)
    end
  end
end

function Backend.ellipse(cx, cy, rx, ry, ds)
  if ds.hasFill then
    setFill(ds.fillColor)
    love.graphics.ellipse("fill", cx, cy, rx, ry, 64)
  end
  if ds.hasStroke then
    setStroke(ds)
    love.graphics.ellipse("line", cx, cy, rx, ry, 64)
  end
end

function Backend.arc(cx, cy, rx, ry, startAngle, stopAngle, mode, ds)
  -- LOVE's arc function signature: arc(drawmode, arctype, x, y, radius, a1, a2, segments)
  -- For ellipses we tessellate
  local arcType = "open"
  if mode == "PIE" then arcType = "pie"
  elseif mode == "CHORD" then arcType = "open" end

  -- Approximate as ellipse sector
  local steps = math.max(16, math.floor(math.abs(stopAngle - startAngle) / (math.pi * 2) * 64))
  local pts = {}

  if mode == "PIE" then
    pts[#pts+1] = cx
    pts[#pts+1] = cy
  end

  local span = stopAngle - startAngle
  for i = 0, steps do
    local a = startAngle + (i / steps) * span
    pts[#pts+1] = cx + math.cos(a) * rx
    pts[#pts+1] = cy + math.sin(a) * ry
  end

  if mode == "CHORD" then
    -- close with a line from end back to start
    pts[#pts+1] = cx + math.cos(startAngle) * rx
    pts[#pts+1] = cy + math.sin(startAngle) * ry
  end

  if #pts >= 6 then
    if ds.hasFill then
      setFill(ds.fillColor)
      love.graphics.polygon("fill", pts)
    end
    if ds.hasStroke then
      setStroke(ds)
      love.graphics.polygon("line", pts)
    end
  end
end

function Backend.triangle(ax, ay, bx, by, cx, cy, ds)
  if ds.hasFill then
    setFill(ds.fillColor)
    love.graphics.polygon("fill", ax, ay, bx, by, cx, cy)
  end
  if ds.hasStroke then
    setStroke(ds)
    love.graphics.polygon("line", ax, ay, bx, by, cx, cy)
  end
end

function Backend.quad(ax, ay, bx, by, cx, cy, dx, dy, ds)
  if ds.hasFill then
    setFill(ds.fillColor)
    love.graphics.polygon("fill", ax, ay, bx, by, cx, cy, dx, dy)
  end
  if ds.hasStroke then
    setStroke(ds)
    love.graphics.polygon("line", ax, ay, bx, by, cx, cy, dx, dy)
  end
end

function Backend.polyline(pts, ds)
  if not ds.hasStroke then return end
  setStroke(ds)
  local flat = {}
  for _, v in ipairs(pts) do
    flat[#flat+1] = v.x
    flat[#flat+1] = v.y
  end
  if #flat >= 4 then
    love.graphics.line(flat)
  end
end

function Backend.shape(verts, kind, closed, ds)
  local flat = {}
  for _, v in ipairs(verts) do
    flat[#flat+1] = v.x
    flat[#flat+1] = v.y
  end

  if kind == nil then
    -- Default polygon
    if #flat >= 6 then
      if ds.hasFill then
        setFill(ds.fillColor)
        love.graphics.polygon("fill", flat)
      end
      if ds.hasStroke then
        setStroke(ds)
        if closed then
          love.graphics.polygon("line", flat)
        else
          love.graphics.line(flat)
        end
      end
    end
  elseif kind == "LINES" then
    if ds.hasStroke and #flat >= 4 then
      setStroke(ds)
      for i = 1, #verts - 1, 2 do
        love.graphics.line(verts[i].x, verts[i].y, verts[i+1].x, verts[i+1].y)
      end
    end
  elseif kind == "POINTS" then
    for _, v in ipairs(verts) do
      Backend.point(v.x, v.y, ds)
    end
  elseif kind == "TRIANGLES" then
    for i = 1, #verts - 2, 3 do
      Backend.triangle(
        verts[i].x, verts[i].y,
        verts[i+1].x, verts[i+1].y,
        verts[i+2].x, verts[i+2].y,
        ds
      )
    end
  elseif kind == "TRIANGLE_FAN" then
    local center = verts[1]
    for i = 2, #verts - 1 do
      Backend.triangle(center.x, center.y, verts[i].x, verts[i].y, verts[i+1].x, verts[i+1].y, ds)
    end
  elseif kind == "TRIANGLE_STRIP" then
    for i = 1, #verts - 2 do
      if i % 2 == 1 then
        Backend.triangle(verts[i].x,verts[i].y, verts[i+1].x,verts[i+1].y, verts[i+2].x,verts[i+2].y, ds)
      else
        Backend.triangle(verts[i+1].x,verts[i+1].y, verts[i].x,verts[i].y, verts[i+2].x,verts[i+2].y, ds)
      end
    end
  elseif kind == "QUADS" then
    for i = 1, #verts - 3, 4 do
      Backend.quad(
        verts[i].x,verts[i].y, verts[i+1].x,verts[i+1].y,
        verts[i+2].x,verts[i+2].y, verts[i+3].x,verts[i+3].y,
        ds
      )
    end
  end
end

-- ============================================================
-- Image
-- ============================================================

function Backend.loadImage(path)
  local ok, img = pcall(love.graphics.newImage, path)
  if ok then
    return { _love = img, width = img:getWidth(), height = img:getHeight() }
  end
  return nil
end

function Backend.image(img, x, y, w, h, ds)
  if not img or not img._love then return end
  local tint = ds.hasTint and ds.tintColor or { r=1, g=1, b=1, a=1 }
  love.graphics.setColor(tint.r, tint.g, tint.b, tint.a)
  if w and h then
    local sx = w / img._love:getWidth()
    local sy = h / img._love:getHeight()
    love.graphics.draw(img._love, x, y, 0, sx, sy)
  else
    love.graphics.draw(img._love, x, y)
  end
end

-- ============================================================
-- Text
-- ============================================================

local _currentFont = nil
local _fontCache   = {}

local function getFont(size)
  local key = tostring(size)
  if not _fontCache[key] then
    _fontCache[key] = love.graphics.newFont(size)
  end
  return _fontCache[key]
end

function Backend.textSize(sz)
  _currentFont = getFont(sz)
  love.graphics.setFont(_currentFont)
end

function Backend.text(str, x, y, w, h, ds)
  local font = getFont(ds.textSz or 12)
  love.graphics.setFont(font)
  setFill(ds.fillColor)
  local alignH = ds.textAlignH
  local loveAlign = "left"
  if alignH == "CENTER" then loveAlign = "center"
  elseif alignH == "RIGHT" then loveAlign = "right" end

  if w then
    love.graphics.printf(str, x, y, w, loveAlign)
  else
    love.graphics.print(str, x, y)
  end
end

function Backend.textWidth(str, ds)
  local font = getFont(ds.textSz or 12)
  return font:getWidth(str)
end

function Backend.textAscent(ds)
  local font = getFont(ds.textSz or 12)
  return font:getAscent()
end

function Backend.textDescent(ds)
  local font = getFont(ds.textSz or 12)
  return font:getDescent()
end

-- ============================================================
-- Timing
-- ============================================================

function Backend.millis()
  return (love.timer.getTime() - _startTime) * 1000
end

function Backend.setFrameRate(fps)
  -- LOVE respects vsync; we can cap via a simple limiter
  -- Not directly settable in LOVE; handled in the run loop
end

-- ============================================================
-- Cursor
-- ============================================================

function Backend.cursor(cursorType)
  love.mouse.setVisible(true)
end

function Backend.noCursor()
  love.mouse.setVisible(false)
end

-- ============================================================
-- Main run loop (LOVE2D entry points)
-- ============================================================

function Backend.run(env, pState, P)
  _P      = P
  _env    = env
  _pState = pState

  -- Override LOVE2D callbacks so the sketch drives the window

  function love.update(dt)
    -- Update mouse state
    local mx, my = love.mouse.getPosition()
    local mb1    = love.mouse.isDown(1)
    local btn    = nil
    if love.mouse.isDown(1) then btn = "LEFT"
    elseif love.mouse.isDown(2) then btn = "RIGHT"
    elseif love.mouse.isDown(3) then btn = "CENTER" end
    P._setMouse(mx, my, mb1, btn)
  end

  function love.draw()
    P._frame(env)
  end

  function love.keypressed(key, scancode, isrepeat)
    P._setKey(true, key, love.keyboard.getScancodeFromKey(key) or 0)
    local kp = env.keyPressed or rawget(_G or {}, "keyPressed")
    if type(kp) == "function" then kp() end
  end

  function love.keyreleased(key)
    P._setKey(false, "", 0)
    local kr = env.keyReleased or rawget(_G or {}, "keyReleased")
    if type(kr) == "function" then kr() end
  end

  function love.mousepressed(x, y, button)
    local mp = env.mousePressed or rawget(_G or {}, "mousePressed")
    if type(mp) == "function" then mp() end
  end

  function love.mousereleased(x, y, button)
    local mr = env.mouseReleased or rawget(_G or {}, "mouseReleased")
    if type(mr) == "function" then mr() end
  end

  function love.mousemoved(x, y, dx, dy)
    local mm = env.mouseMoved or rawget(_G or {}, "mouseMoved")
    if type(mm) == "function" then mm() end
  end

  function love.quit()
    local ef = env.exit or rawget(_G or {}, "exit")
    if type(ef) == "function" then ef() end
  end

  -- LOVE2D launches its loop automatically; no explicit loop needed here.
end

return Backend
